version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  ignore:
  # Ignore ESM-only package versions.
  # This can be fully removed once everything is ESM-native without all the weird issues.
  - dependency-name: hook-std
    versions:
    - '3.x'
  - dependency-name: node-fetch
    versions:
    - '3.x'
  - dependency-name: to-readable-stream
    versions:
    - '3.x'
